http:
  middlewares:
    oidc-auth:
      plugin:
       traefik-oidc-auth:
         Secret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         Provider:
           ClientId: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           ClientSecret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           Url: https://auth.tuservidor.es
           TokenValidation: IdToken
         Scopes:
           - openid
           - profile
           - email


  routers:
    dashboard:
      rule: Host(`traefik.tuservidor.es`) # El subdominio para tu panel
      service: api@internal
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver
      middlewares:
        - oidc-auth
        - compresionHeaders
        - seguridadHeaders
